---

#- name: Install curl
#  apt: name=curl state=present
#
#- name: Check for datastax repo key presence
#  shell: "apt-key list | grep B999A372"
#  register: apt_key
#  failed_when: False
#  changed_when: False

#- name: Get datastax repo_key
#  shell: curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
#  when: apt_key.rc != 0

#- name: Add datastax repo
#  apt_repository: repo='deb http://debian.datastax.com/community stable main' state=present
#  retries: 3

#- name: apt-get update
#  apt:
#    update_cache: yes
#  when: apt_key.rc != 0

- name: Install cassandra
  apt:
    pkg: "{{ item }}"
    state: present
    allow_unauthenticated: yes
  register: cass_package
  with_items:
    - cassandra={{ cass_version }}
    - cassandra-tools
  notify:
    - Stop cassandra
    - Clear cassandra data dir

- name: Change data dir permision
  command: sudo chown cassandra:cassandra {{ base_dir }}
  notify:
    - Restart cassandra
- meta: flush_handlers
