---
# handlers file for cassandra
- name: Stop cassandra
  service: name=cassandra state=stopped

- name: Start cassandra
  service: name=cassandra state=started

- name: Restart cassandra
  service: name=cassandra state=restarted

- name: Clear cassandra data dir
  shell: rm -rf {{ data_dir }}/*
  notify:  Clear cassandra commitlog dir

- name: Clear cassandra commitlog dir
  shell: rm -rf {{ commitlog_dir }}/*
  notify:  Clear cassandra saved_caches dir

- name: Clear cassandra saved_caches dir
  shell: rm -rf {{ saved_caches_dir }}/*
